import { Link } from "react-router-dom"
import { ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"

export function Article() {
  return (
    <div className="relative flex min-h-screen w-full flex-col">
      <main className="mx-auto w-full max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="mb-8">
          <Button variant="ghost" asChild>
            <Link to="/feed">
              <ArrowLeft className="mr-2 h-5 w-5" />
              <span>Back</span>
            </Link>
          </Button>
        </div>
        <article className="prose prose-lg dark:prose-invert max-w-none prose-p:text-lg prose-p:leading-relaxed prose-h1:text-4xl prose-h1:font-bold">
          <h1>Tech Giant Unveils Revolutionary AI-Powered News Aggregator</h1>
          <p className="text-muted-foreground">
            In a groundbreaking move, tech giant Innovatech has launched Flash News AI, an
            AI-driven news aggregator poised to redefine how users consume news. This innovative
            platform leverages cutting-edge artificial intelligence to curate personalized news
            feeds, ensuring users receive the most relevant and engaging content tailored to their
            interests.
          </p>
          <p className="text-muted-foreground">
            Flash News AI employs sophisticated algorithms to analyze user preferences, reading
            habits, and social media interactions, creating a dynamic profile that evolves with the
            user's changing interests. This personalized approach eliminates the noise of
            irrelevant news, delivering a focused and efficient news consumption experience.
          </p>
          <p className="text-muted-foreground">
            The platform's intuitive interface allows users to easily navigate through various news
            categories, including technology, business, politics, sports, and entertainment. Each
            article is accompanied by a concise summary generated by AI, providing a quick overview
            of the content before diving into the full story. Users can also customize their news
            feed by selecting specific topics, keywords, and sources, ensuring they stay informed
            about the news that matters most to them.
          </p>
          <p className="text-muted-foreground">
            Innovatech's commitment to accuracy and reliability is evident in Flash News AI's
            rigorous fact-checking mechanisms. The platform cross-references information from
            multiple reputable sources, flagging potentially misleading or inaccurate content. This
            feature aims to combat the spread of misinformation, providing users with a
            trustworthy and credible news source.
          </p>
          <p className="text-muted-foreground">
            Flash News AI also incorporates a social element, allowing users to share articles,
            comment on stories, and engage in discussions with other readers. This fosters a sense
            of community and encourages diverse perspectives on current events. The platform's
            comment moderation system ensures a respectful and constructive environment for user
            interactions.
          </p>
          <p className="text-muted-foreground">
            The launch of Flash News AI marks a significant advancement in the field of news
            aggregation, promising a more personalized, efficient, and reliable news consumption
            experience. As the platform continues to evolve and refine its algorithms, it is poised
            to become an indispensable tool for staying informed in today's fast-paced world.
          </p>
        </article>
      </main>
    </div>
  )
}

